name: Tests (pytest)

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    
    steps:
      - name: Checkout ref
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ytmusicapi
          pip install pytest pytest-recording pytest-xdist pytest-sugar

      - name: Live or recorded tests?
        uses: ddradar/choose-random-action@v1
        id: is_live_test
        with:
          contents: |
            1
            0
          weights: |
            33
            67
              
      - name: Run Tests (live)
        if: ${{ steps.is_live_test.outputs.selected == 1 }}
        run: |
          pytest -n 4 --record-mode=rewrite

      - name: Run Tests (from recordings)
        if: ${{ steps.is_live_test.outputs.selected == 0 }}
        run: |
          pytest -n 4